[[permission]]
identifier = "app-commands"
description = "Allow custom app commands"

commands.allow = [
    "save_file_dialog",
    "open_containing_folder",
    "open_file_with_player",
    "download_file_dialog"
]
